FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=development

# Install dependencies first (cached)
COPY package*.json ./
RUN npm install

# Create src directory (will be mounted)
RUN mkdir -p /app/src

EXPOSE 3000

# Run nodemon from src
CMD ["npm", "run", "dev"]
