worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/product {
            proxy_pass http://express-api:3001/product/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/product/ {
            proxy_pass http://express-api:3001/product/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }


        location / {
            proxy_pass http://react-app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}