# -------- DEV CONFIG --------
CONTAINER_NAME="mongodb-dev"
IMAGE="mongodb/mongodb-community-server:7.0-ubuntu2204"
PORT="27018"

NETWORK_NAME="mongo-net-dev"
VOLUME_NAME="mongo-data-dev"

USERNAME="dev_user"
PASSWORD="dev_secret"
