# -------- PROD CONFIG --------
CONTAINER_NAME="mongodb-prod"
IMAGE="mongodb/mongodb-community-server:7.0-ubuntu2204"
PORT="27017"

NETWORK_NAME="mongo-net-prod"
VOLUME_NAME="mongo-data-prod"

USERNAME="admin"
PASSWORD="secret"
